esphome:
  name: rs485_receiver

esp32:
  board: esp32dev

logger:

uart:
  id: uart_rs485
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  debug:
    direction: RX
    dummy_receiver: true
    after:
      delimiter: "\n"
    sequence:
      - lambda: |-
          UARTDebug::log_string(direction, bytes);